set encoding=utf-8
scriptencoding utf-8

" General 
set tabstop=4
set shiftwidth=4
set noswapfile
set noerrorbells

" Line number stuff
set relativenumber
set number
set numberwidth=8

" Sane searching 
set hlsearch 
set incsearch 
set smartcase
set ignorecase

" Save searches
set viminfo+=/10000

" File management
set nohidden
set autowrite

" Don't hide any files from completion
set wildignore=

" Put swap files in ~/.vim/swap/.
" For Unix, if a directory ends in two path seperators "//"
" The swap file name will be built from the complete path to 
" the file with all path seperators substituted to percent '%'
" signs. This will ensure file name uniqueness in the preserve
" directory.
set directory=~/.vim/swap//,.

" filename [Help][-][RO]
set statusline=\ \ \ %<%f\ %h%m%r

" Command line 
set wildmenu
set wildmode=longest,full

" Terminal 
" Treat undercurl as underline
set t_Cs=
set t_Ce=

" Syntax highlighting
syntax on
filetype on
filetype indent on
filetype plugin on

" Custom Maps
nnoremap <C-N> :bnext<CR>
nnoremap <C-P> :bprev<CR>
nnoremap <C-N> :bnext<CR>

" fix: Map a key binding to a custom function call that autocmd plugins
"noremap <C-I> :execute <SID>dev#plugins#plug_install()<CR>

map <c-d> dd
" Delete the current line, then paste it below the one we are one (move the
" line down one
map - ddp

" Import plugins
" autoload/dev/plugins
if filereadable(expand("~/dotfiles/vim/vim/ftplugin/.vimrc-plugins"))
        source ~/dotfiles/vim/vim/ftplugin/.vimrc-plugins
endif

call dev#filetype#filetype_auto_start()
call dev#nerdtree#nerdtree_auto_start()

" Colorscheming
set background=dark
colorscheme gruvbox

" Must be last. This command is dangerous due to vim running everything 
" listed in the *.vim files
set exrc secure
