# Git related stuff
alias gs="git status -s -b"
alias gc="git commit -v"
alias g.="git add -p"
alias gi="git add -i" # Different from Vim
alias g?="git diff"
alias g??="git diff --cached" # Different from Vim
alias gv="git pull --ff --commit"
alias g^="git push"
alias gp="git checkout -p"

alias go="git checkout"

# Command Line
## (ls))
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

## (cd)
alias cd.="cd ../"
alias cd..="cd ../../"
alias cd...="cd ../../../"

# Enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

